import json
import os

import pytest

from depscan.lib import explainer


@pytest.fixture
def test_data():
    with open(
        os.path.join(
            os.path.dirname(os.path.realpath(__file__)),
            "data",
            "reachables.slices.json",
        ),
        mode="r",
        encoding="utf-8",
    ) as fp:
        return json.load(fp)


def test_explain_reachables(test_data, capsys):
    explainer.explain_reachables(test_data, {}, "java")
    captured = capsys.readouterr()
    if os.getenv("OS") == "Windows-NT":
        assert captured.out == ('\n'
                                '\x1b[1;3m#1\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mreq\x1b[0m\x1b[3m ↩ to '
                                'the method \x1b[0m\x1b[1;3mvuln04\x1b[0m\x1b[3m can be used to reach this '
                                'package.     \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Cookies.java#62    '
                                '\x1b[0mvuln04(\x1b[31mreq\x1b[0m) ↩                     ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#64    '
                                '\x1b[0mreq.getCookies()              ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#65    \x1b[0mcookies '
                                '!= null               ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#66    '
                                '\x1b[0m<empty>                       ║\n'
                                '║ ├── '
                                'cookie                                                                  ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#67    '
                                '\x1b[0mcookie.getName()              ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#68    '
                                '\x1b[0mcookie.getValue()             ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Cookies.java#72    \x1b[0m"Cookie '
                                'nick: " + nick        ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#2\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mbuilder\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mrestTemplate\x1b[0m\x1b[3m can be used to '
                                'reach 2       \x1b[0m\n'
                                '\x1b[3mpackages.                                                                      '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/config/HttpServiceConfig.java#34    '
                                '\x1b[0mrestTemplate(\x1b[31mbuilder\x1b[0m) ↩     ║\n'
                                '║ '
                                '\x1b[1mTags:\x1b[0m                                                                       '
                                '║\n'
                                '║ '
                                '\x1b[3mpkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar, '
                                '\x1b[0m     ║\n'
                                '║ \x1b[3mframework, '
                                'framework-input\x1b[0m                                                  ║\n'
                                '║                                                                             '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/config/HttpServiceConfig.java#35    '
                                '\x1b[0mbuilder.build()         ║\n'
                                '║     '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║     '
                                '\x1b[3mpkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar, '
                                '\x1b[0m ║\n'
                                '║     '
                                '\x1b[3mframework-value\x1b[0m                                                         '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar        '
                                '\x1b[0m\n'
                                '\x1b[2;3m     '
                                'pkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar     '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#3\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mtoken\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mgetCsrfToken1\x1b[0m\x1b[3m can be used to '
                                'reach this     \x1b[0m\n'
                                '\x1b[3mpackage.                                                                       '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#111    '
                                '\x1b[0mgetCsrfToken1(\x1b[31mtoken\x1b[0m) ↩             ║\n'
                                '║ \x1b[1mTags:\x1b[0m \x1b[3mframework-input, '
                                '\x1b[0m                                                     ║\n'
                                '║ '
                                '\x1b[3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEAS…\x1b[0m '
                                '║\n'
                                '║ '
                                '\x1b[3mframework\x1b[0m                                                                   '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#112    \x1b[0mreturn '
                                'token;                  ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEASE?typ\x1b[0m\n'
                                '\x1b[2;3m                                     '
                                'e=jar                                     \x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#4\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mrequest\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mgetCsrfToken2\x1b[0m\x1b[3m can be used to '
                                'reach 2      \x1b[0m\n'
                                '\x1b[3mpackages.                                                                      '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#121    '
                                '\x1b[0mgetCsrfToken2(\x1b[31mrequest\x1b[0m) ↩           ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#122    '
                                '\x1b[0m                               ║\n'
                                '║ │   '
                                'cookieCsrfTokenRepository.loadToken(request)                            ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#129    '
                                '\x1b[0mcsrfToken.toString()           ║\n'
                                '║     '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║     '
                                '\x1b[3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RE…\x1b[0m '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEASE?typ\x1b[0m\n'
                                '\x1b[2;3m                                     '
                                'e=jar                                     \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#5\x1b[0m\x1b[3m Method \x1b[0m\x1b[3;31memptyReferer\x1b[0m\x1b[3m '
                                '↩ can be used to reach 2 packages.                      \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#53    \x1b[0memptyReferer() '
                                '↩                    ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#59    '
                                '\x1b[0mthis.callback                   ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#60    '
                                '\x1b[0m                                ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#13    '
                                '\x1b[0mgetUserInfo2JsonStr(\x1b[31mrequest\x1b[0m) ↩   ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#14    '
                                '\x1b[0mrequest.getUserPrincipal()       ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#15    '
                                '\x1b[0mprincipal.getName()              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#19    '
                                '\x1b[0mJSON.toJSONString(m)             ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#60    '
                                '\x1b[0m                                ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#30    '
                                '\x1b[0mjson2Jsonp(\x1b[31mjsonStr\x1b[0m) ↩              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#31    '
                                '\x1b[0mHtmlUtils.htmlEscape(callback) +   ║\n'
                                '║ │   "(" + jsonStr + '
                                '")"                                                     ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#60    '
                                '\x1b[0mWebUtils.json2Jsonp(callback,   ║\n'
                                '║     '
                                'LoginUtils.getUserInfo2JsonStr(request))                                ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                '
                                'pkg:maven/com.alibaba/fastjson@1.2.24?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#6\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mfilepath\x1b[0m\x1b[3m '
                                '↩ to the method \x1b[0m\x1b[1;3mgetImageSec\x1b[0m\x1b[3m can be used to '
                                'reach this    \x1b[0m\n'
                                '\x1b[3mpackage.                                                                       '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/PathTraversal.java#30    '
                                '\x1b[0mgetImageSec(\x1b[31mfilepath\x1b[0m) ↩     ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/security/SecurityUtil.java#178    '
                                '\x1b[0mpathFilter(\x1b[31mfilepath\x1b[0m) ↩    ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/PathTraversal.java#38    '
                                '\x1b[0mgetImgBase64(\x1b[31mimgFile\x1b[0m) ↩ ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/PathTraversal.java#45    '
                                '\x1b[0mPaths.get(imgFile)      ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/PathTraversal.java#46    '
                                '\x1b[0m                        ║\n'
                                '║ │   '
                                'Base64.encodeBase64(data)                                               ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/PathTraversal.java#35    '
                                '\x1b[0m                        ║\n'
                                '║     '
                                'this.getImgBase64(filepath)                                             ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/commons-collections/commons-collections@3.1?type=jar         '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#7\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mrequest\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mappInfo\x1b[0m\x1b[3m can be used to reach 2 '
                                'packages.  \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Index.java#26    '
                                '\x1b[0mappInfo(\x1b[31mrequest\x1b[0m) ↩                  ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Index.java#27    '
                                '\x1b[0mrequest.getUserPrincipal()      ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Index.java#35    '
                                '\x1b[0mJSON.VERSION                    ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Index.java#38    '
                                '\x1b[0mJSON.toJSONString(m)            ║\n'
                                '║     \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/com.alibaba/fastjson@1.2.24?type=jar, json, '
                                'parse\x1b[0m       ║\n'
                                '║                                                                             '
                                '║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                '
                                'pkg:maven/com.alibaba/fastjson@1.2.24?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#8\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mrequest\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mproxy\x1b[0m\x1b[3m can be used to reach this '
                                'package.  \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/IPForge.java#33    '
                                '\x1b[0mproxy(\x1b[31mrequest\x1b[0m) ↩                  ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/IPForge.java#34    '
                                '\x1b[0m                              ║\n'
                                '║ │   '
                                'request.getHeader("X-Real-IP")                                          ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/IPForge.java#36    \x1b[0mreturn '
                                'ip;                    ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#9\x1b[0m\x1b[3m Method \x1b[0m\x1b[3;31msafecode\x1b[0m\x1b[3m ↩ '
                                'can be used to reach 2 packages.                          \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#95    \x1b[0msafecode() '
                                '↩                        ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#101    '
                                '\x1b[0mthis.callback                  ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#102    '
                                '\x1b[0m                               ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#13    '
                                '\x1b[0mgetUserInfo2JsonStr(\x1b[31mrequest\x1b[0m) ↩   ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#14    '
                                '\x1b[0mrequest.getUserPrincipal()       ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#15    '
                                '\x1b[0mprincipal.getName()              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#19    '
                                '\x1b[0mJSON.toJSONString(m)             ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#102    '
                                '\x1b[0m                               ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#30    '
                                '\x1b[0mjson2Jsonp(\x1b[31mjsonStr\x1b[0m) ↩              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#31    '
                                '\x1b[0mHtmlUtils.htmlEscape(callback) +   ║\n'
                                '║ │   "(" + jsonStr + '
                                '")"                                                     ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#102    '
                                '\x1b[0mWebUtils.json2Jsonp(callback,  ║\n'
                                '║     '
                                'LoginUtils.getUserInfo2JsonStr(request))                                ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                '
                                'pkg:maven/com.alibaba/fastjson@1.2.24?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#10\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mreq\x1b[0m\x1b[3m ↩ to '
                                'the method \x1b[0m\x1b[1;3mproxyInject\x1b[0m\x1b[3m can be used to reach '
                                'this        \x1b[0m\n'
                                '\x1b[3mpackage.                                                                       '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/WebSockets.java#54    '
                                '\x1b[0mproxyInject(\x1b[31mreq\x1b[0m) ↩             ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/WebSockets.java#55    '
                                '\x1b[0mreq.getParameter("path")   ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/WebSockets.java#59    '
                                '\x1b[0mreq.getServletContext()    ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/WebSockets.java#62    '
                                '\x1b[0m                           ║\n'
                                '║ │   '
                                'sc.getAttribute(ServerContainer.class.getName())                        ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/WebSockets.java#63    '
                                '\x1b[0mwsc.findMapping(path)      ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/WebSockets.java#69    \x1b[0m"[-] '
                                'Websocket: " + path + ║\n'
                                '║     " has been '
                                'injected!"                                                   ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#11\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mreq\x1b[0m\x1b[3m ↩ to '
                                'the method \x1b[0m\x1b[1;3mvuln01\x1b[0m\x1b[3m can be used to reach 2 '
                                'packages.      \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Cookies.java#26    '
                                '\x1b[0mvuln01(\x1b[31mreq\x1b[0m) ↩                     ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#27    '
                                '\x1b[0m                              ║\n'
                                '║ │   WebUtils.getCookieValueByName(req, '
                                'NICK)                                ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#24    '
                                '\x1b[0mgetCookieValueByName(\x1b[31mrequest\x1b[0m) ↩    ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#25    '
                                '\x1b[0m                                   ║\n'
                                '║ │   org.springframework.web.util.WebUtils.getCookie(request, '
                                'cookieName)    ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#26    \x1b[0mcookie == '
                                'null                     ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cookies.java#27    '
                                '\x1b[0m                              ║\n'
                                '║ │   WebUtils.getCookieValueByName(req, '
                                'NICK)                                ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Cookies.java#28    \x1b[0m"Cookie '
                                'nick: " + nick        ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar        '
                                '\x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#12\x1b[0m\x1b[3m Parameter '
                                '\x1b[0m\x1b[3;31mmultifile\x1b[0m\x1b[3m ↩ to the method '
                                '\x1b[0m\x1b[1;3muploadPicture\x1b[0m\x1b[3m can be used to reach 2   '
                                '\x1b[0m\n'
                                '\x1b[3mpackages.                                                                      '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/FileUpload.java#84    '
                                '\x1b[0muploadPicture(\x1b[31mmultifile\x1b[0m) ↩     ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar, '
                                '\x1b[0m     ║\n'
                                '║ \x1b[3mframework, framework-input, '
                                'web\x1b[0m                                             ║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#85    '
                                '\x1b[0mmultifile.isEmpty()        ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar, '
                                '\x1b[0m ║\n'
                                '║ │   '
                                '\x1b[3mweb\x1b[0m                                                                     '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#89    '
                                '\x1b[0m                           ║\n'
                                '║ │   '
                                'multifile.getOriginalFilename()                                         ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar, '
                                '\x1b[0m ║\n'
                                '║ │   '
                                '\x1b[3mweb\x1b[0m                                                                     '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#90    '
                                '\x1b[0mfileName.lastIndexOf(".")  ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#92    '
                                '\x1b[0mUPLOADED_FOLDER + fileName ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#157    '
                                '\x1b[0mdeleteFile(\x1b[31mfilePath\x1b[0m) ↩    ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#161    \x1b[0m"[+] '
                                '" + filePath + "     ║\n'
                                '║ │   delete '
                                'successfully!"                                                   ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#157    '
                                '\x1b[0mRET                       ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#152    '
                                '\x1b[0mthis.logger               ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/FileUpload.java#153    '
                                '\x1b[0mthis.logger               ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/FileUpload.java#154    '
                                '\x1b[0mString.format("You        ║\n'
                                '║     successfully uploaded \'%s\'", '
                                'filePath)                                  ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                 '
                                'pkg:maven/org.slf4j/slf4j-api@1.7.22?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar        '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#13\x1b[0m\x1b[3m Method \x1b[0m\x1b[3;31mreferer\x1b[0m\x1b[3m ↩ '
                                'can be used to reach 2 packages.                          \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#41    \x1b[0mreferer() '
                                '↩                         ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#43    '
                                '\x1b[0mthis.callback                   ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#44    '
                                '\x1b[0m                                ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#13    '
                                '\x1b[0mgetUserInfo2JsonStr(\x1b[31mrequest\x1b[0m) ↩   ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#14    '
                                '\x1b[0mrequest.getUserPrincipal()       ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#15    '
                                '\x1b[0mprincipal.getName()              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#19    '
                                '\x1b[0mJSON.toJSONString(m)             ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#44    '
                                '\x1b[0m                                ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#30    '
                                '\x1b[0mjson2Jsonp(\x1b[31mjsonStr\x1b[0m) ↩              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#31    '
                                '\x1b[0mHtmlUtils.htmlEscape(callback) +   ║\n'
                                '║ │   "(" + jsonStr + '
                                '")"                                                     ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#44    '
                                '\x1b[0mWebUtils.json2Jsonp(callback,   ║\n'
                                '║     '
                                'LoginUtils.getUserInfo2JsonStr(request))                                ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                '
                                'pkg:maven/com.alibaba/fastjson@1.2.24?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#14\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mbuilder\x1b[0m\x1b[3m '
                                '↩ to the method \x1b[0m\x1b[1;3mrestTemplateBanRedirects\x1b[0m\x1b[3m can '
                                'be used to  \x1b[0m\n'
                                '\x1b[3mreach 2 '
                                'packages.                                                              '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/config/HttpServiceConfig.java#28    '
                                '\x1b[0m                            ║\n'
                                '║ restTemplateBanRedirects(\x1b[31mbuilder\x1b[0m) '
                                '↩                                         ║\n'
                                '║ '
                                '\x1b[1mTags:\x1b[0m                                                                       '
                                '║\n'
                                '║ '
                                '\x1b[3mpkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar, '
                                '\x1b[0m     ║\n'
                                '║ \x1b[3mframework, '
                                'framework-input\x1b[0m                                                  ║\n'
                                '║                                                                             '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/config/HttpServiceConfig.java#29    '
                                '\x1b[0m                        ║\n'
                                '║     '
                                'builder.requestFactory(CustomClientHttpRequestFactory.class)            ║\n'
                                '║     '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║     '
                                '\x1b[3mpkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar, '
                                '\x1b[0m ║\n'
                                '║     '
                                '\x1b[3mframework-value\x1b[0m                                                         '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar        '
                                '\x1b[0m\n'
                                '\x1b[2;3m     '
                                'pkg:maven/org.springframework.boot/spring-boot@1.5.1.RELEASE?type=jar     '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#15\x1b[0m\x1b[3m Method '
                                '\x1b[0m\x1b[3;31mgetCsrfToken2\x1b[0m\x1b[3m ↩ can be used to reach this '
                                'package.                  \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Jsonp.java#120    '
                                '\x1b[0mgetCsrfToken2() ↩                  ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Jsonp.java#122    '
                                '\x1b[0mthis.cookieCsrfTokenRepository ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Jsonp.java#129    '
                                '\x1b[0mcsrfToken.toString()           ║\n'
                                '║     '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║     '
                                '\x1b[3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RE…\x1b[0m '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEASE?typ\x1b[0m\n'
                                '\x1b[2;3m                                     '
                                'e=jar                                     \x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#16\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mfile\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mooxml_xxe\x1b[0m\x1b[3m can be used to reach 2 '
                                'packages.  \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#45    '
                                '\x1b[0mooxml_xxe(\x1b[31mfile\x1b[0m) ↩     ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar, '
                                '\x1b[0m     ║\n'
                                '║ \x1b[3mframework, framework-input, '
                                'web\x1b[0m                                             ║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#46    '
                                '\x1b[0m                  ║\n'
                                '║ │   '
                                'file.getInputStream()                                                   ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar, '
                                '\x1b[0m ║\n'
                                '║ │   '
                                '\x1b[3mweb\x1b[0m                                                                     '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#48    '
                                '\x1b[0mwb.getSheetAt(0)  ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar, '
                                'api\x1b[0m             ║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#52    '
                                '\x1b[0m                  ║\n'
                                '║ │   '
                                'sheet.rowIterator()                                                     ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar, '
                                'api\x1b[0m             ║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#57    '
                                '\x1b[0m(XSSFRow)         ║\n'
                                '║ │   '
                                'rows.next()                                                             ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#58    '
                                '\x1b[0m                  ║\n'
                                '║ │   '
                                'row.cellIterator()                                                      ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar, '
                                'api\x1b[0m             ║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#61    '
                                '\x1b[0m(XSSFCell)        ║\n'
                                '║ │   '
                                'cells.next()                                                            ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#63    '
                                '\x1b[0m                  ║\n'
                                '║ │   '
                                'cell.getCellType()                                                      ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar, '
                                'api\x1b[0m             ║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#64    '
                                '\x1b[0m                  ║\n'
                                '║ │   '
                                'cell.getStringCellValue()                                               ║\n'
                                '║ │   \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar, '
                                'api\x1b[0m             ║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/othervulns/ooxmlXXE.java#73    '
                                '\x1b[0m                  ║\n'
                                '║     '
                                'sbResult.toString()                                                     ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m               '
                                'pkg:maven/org.apache.poi/poi@3.10-FINAL?type=jar                \x1b[0m\n'
                                '\x1b[2;3m        '
                                'pkg:maven/org.springframework/spring-web@4.3.6.RELEASE?type=jar        '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#17\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mrequest\x1b[0m\x1b[3m '
                                '↩ to the method \x1b[0m\x1b[1;3mseccode\x1b[0m\x1b[3m can be used to reach 2 '
                                'packages. \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Cors.java#105    '
                                '\x1b[0mseccode(\x1b[31mrequest\x1b[0m) ↩                  ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m ║\n'
                                '║ \x1b[3mtomcat, '
                                'framework-input\x1b[0m                                                     '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cors.java#106    '
                                '\x1b[0mrequest.getHeader("Origin")     ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/Cors.java#115    '
                                '\x1b[0m                                ║\n'
                                '║ │   '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#13    '
                                '\x1b[0mgetUserInfo2JsonStr(\x1b[31mrequest\x1b[0m) ↩   ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#14    '
                                '\x1b[0mrequest.getUserPrincipal()       ║\n'
                                '║ │   '
                                '\x1b[1mTags:\x1b[0m                                                                   '
                                '║\n'
                                '║ │   '
                                '\x1b[3mpkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar, '
                                '\x1b[0m   ║\n'
                                '║ │   '
                                '\x1b[3mtomcat\x1b[0m                                                                  '
                                '║\n'
                                '║ '
                                '│                                                                           '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#15    '
                                '\x1b[0mprincipal.getName()              ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/LoginUtils.java#19    '
                                '\x1b[0mJSON.toJSONString(m)             ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Cors.java#115    '
                                '\x1b[0m                                ║\n'
                                '║     '
                                'LoginUtils.getUserInfo2JsonStr(request)                                 ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                '
                                'pkg:maven/com.alibaba/fastjson@1.2.24?type=jar                 \x1b[0m\n'
                                '\x1b[2;3m      '
                                'pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@8.5.85?type=jar      '
                                '\x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#18\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mtoken\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mgetCsrfToken_04\x1b[0m\x1b[3m can be used to '
                                'reach this  \x1b[0m\n'
                                '\x1b[3mpackage.                                                                       '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Cors.java#99    '
                                '\x1b[0mgetCsrfToken_04(\x1b[31mtoken\x1b[0m) ↩             ║\n'
                                '║ \x1b[1mTags:\x1b[0m \x1b[3mframework-input, '
                                '\x1b[0m                                                     ║\n'
                                '║ '
                                '\x1b[3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEAS…\x1b[0m '
                                '║\n'
                                '║ '
                                '\x1b[3mframework\x1b[0m                                                                   '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Cors.java#100    \x1b[0mreturn '
                                'token;                   ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEASE?typ\x1b[0m\n'
                                '\x1b[2;3m                                     '
                                'e=jar                                     \x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#19\x1b[0m\x1b[3m Parameter \x1b[0m\x1b[3;31mtoken\x1b[0m\x1b[3m ↩ '
                                'to the method \x1b[0m\x1b[1;3mgetCsrfToken_03\x1b[0m\x1b[3m can be used to '
                                'reach this  \x1b[0m\n'
                                '\x1b[3mpackage.                                                                       '
                                '\x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/Cors.java#88    '
                                '\x1b[0mgetCsrfToken_03(\x1b[31mtoken\x1b[0m) ↩             ║\n'
                                '║ \x1b[1mTags:\x1b[0m \x1b[3mframework-input, '
                                '\x1b[0m                                                     ║\n'
                                '║ '
                                '\x1b[3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEAS…\x1b[0m '
                                '║\n'
                                '║ '
                                '\x1b[3mframework\x1b[0m                                                                   '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/Cors.java#89    \x1b[0mreturn '
                                'token;                    ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3mpkg:maven/org.springframework.security/spring-security-crypto@4.2.1.RELEASE?typ\x1b[0m\n'
                                '\x1b[2;3m                                     '
                                'e=jar                                     \x1b[0m\n'
                                '\n'
                                '\x1b[1;3m#20\x1b[0m\x1b[3m Method '
                                '\x1b[0m\x1b[3;31mcodeInjectHost\x1b[0m\x1b[3m ↩ can be used to reach this '
                                'package.                 \x1b[0m\n'
                                '╔═════════════════════════════════════════════════════════════════════════════╗\n'
                                '║ \x1b[38;5;59morg/joychou/controller/CommandInject.java#39    '
                                '\x1b[0mcodeInjectHost() ↩          ║\n'
                                '║ \x1b[1mTags:\x1b[0m '
                                '\x1b[3mframework-input\x1b[0m                                                       '
                                '║\n'
                                '║                                                                             '
                                '║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/CommandInject.java#43    '
                                '\x1b[0mthis.logger             ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/CommandInject.java#44    '
                                '\x1b[0m"curl " + host          ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/CommandInject.java#47    '
                                '\x1b[0mbuilder.start()         ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/controller/CommandInject.java#48    '
                                '\x1b[0m                        ║\n'
                                '║ │   '
                                'process.getInputStream()                                                ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#19    '
                                '\x1b[0mconvertStreamToString(\x1b[31mis\x1b[0m) ↩        ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#20    '
                                '\x1b[0mnew                                ║\n'
                                '║ │   '
                                'java.util.Scanner(is).useDelimiter("\\\\A")                               ║\n'
                                '║ ├── \x1b[38;5;59morg/joychou/util/WebUtils.java#21    \x1b[0ms.hasNext() ? '
                                's.next() : ""        ║\n'
                                '║ └── \x1b[38;5;59morg/joychou/controller/CommandInject.java#48    '
                                '\x1b[0m                        ║\n'
                                '║     '
                                'WebUtils.convertStreamToString(process.getInputStream())                ║\n'
                                '╚═════════════════════════════════════════════════════════════════════════════╝\n'
                                '\x1b[2;3m                              \x1b[0m\x1b[2;3;38;5;66mReachable '
                                'Packages:\x1b[0m\x1b[2;3m                              \x1b[0m\n'
                                '\x1b[2;3m                 '
                                'pkg:maven/org.slf4j/slf4j-api@1.7.22?type=jar                 \x1b[0m\n'
                                '\n'
                                '                              \x1b[1;4mSecure Design '
                                'Tips\x1b[0m                               \n'
                                '\n'
                                '\x1b[1;33m • \x1b[0mConsider implementing a common validation/sanitization '
                                'library to reduce the\n'
                                '\x1b[1;33m   \x1b[0mexploitability '
                                'risk.                                                        \n')
    assert captured.err == ''
