name: Build without publishing

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          uv sync --all-extras --all-packages --dev
          npm install -g @cyclonedx/cdxgen
      - name: Build
        run: |
          uv build --all-packages

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: dist/*
