name: Build without publishing

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          uv sync --all-extras --dev
      - name: Build
        run: |
          uv build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: dist/*
