name: Repo tests Dotnet

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  os-repo-tests:
    strategy:
      fail-fast: true
      matrix:
      # TODO: Restore all the OS and python versions
        os: ['ubuntu-24.04']
        python-version: ['3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'Nova-8/Damm-Vulnerable-dotNet-Application'
          path: 'repotests/Damm-Vulnerable-dotNet-Application'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Trim CI agent
        run: |
          chmod +x contrib/free_disk_space.sh
          ./contrib/free_disk_space.sh
      - name: Install depscan
        run: |
          python -m pip install --upgrade pip
          uv sync --all-extras --all-packages --dev
          npm install -g @cyclonedx/cdxgen
      # LifeCycleAnalyzer tests
      - name: lifecycle-test Damm-Vulnerable-dotNet-Application
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/depscan_reports/Damm-Vulnerable-dotNet-Application-lifecycle
          dotnet build ${GITHUB_WORKSPACE}/repotests/Damm-Vulnerable-dotNet-Application/WebGoat.NET.sln
          uv run depscan --src ${GITHUB_WORKSPACE}/repotests/Damm-Vulnerable-dotNet-Application\
                          --reports-dir ${GITHUB_WORKSPACE}/depscan_reports/Damm-Vulnerable-dotNet-Application\
                          -t dotnet\
                          --vulnerability-analyzer LifecycleAnalyzer
        shell: bash
