name: Repo tests Java

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  os-repo-tests:
    env:
      VDB_DATABASE_URL: "ghcr.io/appthreat/vdbxz-app-2y:v6.5.x"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-24.04']
        python-version: ['3.14']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: 'hoolicorp/java-sec-code'
          path: 'repotests/java-sec-code'
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
        with:
          node-version: '24.x'
          package-manager-cache: false
      - name: Trim CI agent
        run: |
          chmod +x contrib/free_disk_space.sh
          ./contrib/free_disk_space.sh
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install depscan
        run: |
          uv sync --all-extras --all-packages --dev
          npm install -g @cyclonedx/cdxgen
      # LifeCycleAnalyzer tests
      - name: lifecycle-test java-sec-code
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/depscan_reports/java-sec-code-lifecycle
          uv run depscan --src ${GITHUB_WORKSPACE}/repotests/java-sec-code\
                          --reports-dir ${GITHUB_WORKSPACE}/depscan_reports/java-sec-code-lifecycle\
                          -t java\
                          --vulnerability-analyzer LifecycleAnalyzer
        shell: bash
        env:
          BLINTDB_HOME: ${{ runner.temp }}/blintdb-home
